# Generated by Django 5.2.9 on 2025-12-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authprofiles', '0005_passportapplication_allowed_origins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportapplication',
            name='subject',
            field=models.CharField(blank=True, help_text='add a sub claim to the token e.g. OpenUTM', max_length=140),
        ),
    ]
